# UV workspace configuration
[tool.uv.workspace]
members = ["openhands/core", "openhands/tools"]

# Workspace sources for intra-repo dependencies
[tool.uv.sources]
openhands-sdk = { workspace = true }
openhands-tools = { workspace = true }

[dependency-groups]
dev = [
    "pre-commit>=4.3.0",
    "pyright>=1.1.404",
    "ruff>=0.12.10",
]

# Ruff configuration
[tool.ruff]
target-version = "py312"
line-length = 500

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.ruff.lint.isort]
known-first-party = ["benchmarks"]
combine-as-imports = true
force-single-line = false
lines-after-imports = 2
