[project]
name = "openhands_benchmarks_utils"
version = "0.1.0"
description = "Utils for OpenHands benchmarks"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openhands-sdk",
]

[tool.uv.sources]
openhands-sdk = { path = "/home/juan-all-hands/v1/agent-sdk", editable = true }
